import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { validatePolicy } from "../src/policy/validate.js";
import { decide } from "../src/core/verdict.js";
import { isSolanaPubkey } from "../src/transaction/pubkey.js";
import { createReceipt } from "../src/receipts/create.js";
const policy = JSON.parse(readFileSync(new URL("../protocol/examples/clean-policy.json", import.meta.url)));
const program = policy.program_ids[0];
const tx = { program_ids: [program], writable_accounts: [program], lamports: "5000", slippage_bps: 50, accounts: [] };
const args = { policy, transaction: tx, stateTrusted: true, simulation: { ok: true } };
test("valid policy", () => assert.equal(validatePolicy(policy).valid, true));
test("invalid policy", () => assert.equal(validatePolicy({ ...policy, network: "ethereum" }).valid, false));
test("invalid Solana public key", () => assert.equal(isSolanaPubkey("0x123"), false));
test("schema-shaped but invalid 32-byte public key", () => assert.equal(validatePolicy({ ...policy, program_ids: ["123456789ABCDEFGHJKLMNPQRSTUVWXYZ"] }).valid, false));
test("valid Solana public key", () => assert.equal(isSolanaPubkey(program), true));
test("lamport maximum", () => assert.equal(decide({ ...args, transaction: { ...tx, lamports: "100000001" } }).verdict, "DENY"));
test("slippage schema range", () => assert.equal(validatePolicy({ ...policy, max_slippage_bps: 10001 }).valid, false));
test("slippage policy limit", () => assert.equal(decide({ ...args, transaction: { ...tx, slippage_bps: 101 } }).verdict, "DENY"));
test("unknown Program ID", () => assert.equal(decide({ ...args, transaction: { ...tx, program_ids: ["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"] } }).verdict, "QUARANTINE"));
test("unexpected writable account", () => assert.equal(decide({ ...args, transaction: { ...tx, writable_accounts: ["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"] } }).verdict, "DENY"));
test("ALLOW after reference checks", () => assert.equal(decide(args).verdict, "ALLOW"));
test("DENY on expired policy", () => assert.equal(decide({ ...args, policy: { ...policy, expiry: "2020-01-01T00:00:00Z" } }).verdict, "DENY"));
test("QUARANTINE on untrusted state", () => assert.equal(decide({ ...args, stateTrusted: false }).verdict, "QUARANTINE"));
test("QUARANTINE when simulation missing", () => assert.equal(decide({ ...args, simulation: null }).verdict, "QUARANTINE"));
test("QUARANTINE when policy quarantined", () => assert.equal(decide({ ...args, policy: { ...policy, status: "QUARANTINED" } }).verdict, "QUARANTINE"));
test("QUARANTINE on invalid lamport summary", () => assert.equal(decide({ ...args, transaction: { ...tx, lamports: "NaN" } }).verdict, "QUARANTINE"));
test("local receipt generation", () => {
  const receipt = createReceipt({ policyHash: null, objectiveHash: null, stateRoot: null, transaction: { ...tx, accounts: [] }, simulation: { status: "PASS" }, decision: decide(args), checkpoint: "VII" });
  assert.equal(receipt.verdict, "ALLOW");
  assert.equal(receipt.scope, "LOCAL_PROTOCOL_RECEIPT");
  assert.ok(receipt.receipt_id);
});
